springdoc:
  swagger-ui:
    path: /api/docs

document-db:
  connection-string-template: mongodb://%s:%s@%s:%s/%s?directConnection=true&serverSelectionTimeoutMS=2000&tlsAllowInvalidHostnames=true&tls=true&retryWrites=false
